language: python
sudo: required
dist: trusty
matrix:
  include:
    - python: 2.7
    - python: 3.5
    - python: 3.6
install:
  - pip install pycodestyle
  - pip install flake8
  - pip install codecov
  - pip install torch
  - pip install cffi
script:
  - pycodestyle .
  - flake8 .
  - python setup.py install
  - python setup.py test
after_success:
  - codecov
notifications:
  email: false
